#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/utils.sh"


generate_report() {
    local deploy_id="$1"
    local status="$2"
    local duration="$3"
    local git_commit="$4"
    local env_name="$5"
    local strategy="$6"
    local backup_name="$7"
    local report_file="${REPORT_DIR}/deploy_${deploy_id}.md"

    log INFO "Generating deployment report: $report_file"

    cat > "$report_file" <<EOF

| Property         | Value                          |
|------------------|--------------------------------|
| Deployment ID    | \`${deploy_id}\`               |
| Environment      | \`${env_name}\`                |
| Strategy         | \`${strategy}\`                 |
| Git Commit       | \`${git_commit}\`              |
| Status           | \`${status}\`                   |
| Duration         | \`${duration}\`                 |
| Backup           | \`${backup_name}\`              |
| Timestamp        | $(date '+%Y-%m-%d %H:%M:%S') |


\`\`\`
$(tail -n 50 "$LOG_FILE")
\`\`\`

---
*Generated by Automated Deployment System v2.0 (Senior Edition)*
EOF

    log INFO "Report saved: $report_file"

    if command -v pandoc &> /dev/null && command -v wkhtmltopdf &> /dev/null; then
        pandoc "$report_file" -o "${report_file%.md}.pdf" --pdf-engine=wkhtmltopdf 2>/dev/null || true
        log INFO "PDF report generated: ${report_file%.md}.pdf"
    fi
}
